language: rust
rust:
  - stable
branches:
  only:
    - master
env:
  - BUILD_POSTFIX: "--all"
  - BUILD_POSTFIX: "--all --release"
  - FEATURES_POSTFIX: "--features xml"
cache: cargo
install:
  - rustc -Vv
  - cargo -V
script:
  - cargo build --verbose $BUILD_POSTFIX $FEATURES_POSTFIX
  - cargo test --verbose $BUILD_POSTFIX $FEATURES_POSTFIX
